### ISSUE TITLE
Problem binding to interface , errno: 92

### ISSUE THREAD

**Issue by MistEO** [StarAndRabbit/LAN-Scanner#1]
$ ./lanscanner.sh
Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
Problem binding to interface , errno: 92

我是在win10的子系统上跑的

**Comment by tiehichi** [comment]
Linux子系统上限制了raw套接字的使用导致nmap无法在Linux子系统上使用，可以参考这里[“nmap not working”](https://github.com/Microsoft/WSL/issues/2039)
